//go:build linux

package infra

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"
)

const resolvedDropinPath = "/etc/systemd/resolved.conf.d/pier.conf"

// configureHostDNS makes sure .<tld> queries from this host reach pier's
// dnsmasq. Three paths in order of preference:
//
//  1. tailscaled owns /etc/resolv.conf directly: the split-DNS route
//     provided by the coordination server already forwards .<tld> through
//     the tailnet — nothing to do on the host. Returns (false, nil).
//
//  2. systemd-resolved is active: write the per-domain drop-in even when
//     Tailscale DNS is enabled. Tailscale's control-plane status does not
//     prove it successfully configured the host resolver.
//
//  3. Tailscale DNS is enabled without systemd-resolved: rely on its
//     platform-specific DNS integration. Returns (false, nil).
//
// The systemd-resolved path requires sudo, prompting interactively only
// when the drop-in is missing or its content needs to change.
//
// Returns ErrManualDNSNeeded only when neither path applies — the caller
// then falls back to a generic manual-config message.
//
// The bool return reports whether anything was actually written; callers
// use it to decide what to print and whether to mention sudo at all.
func configureHostDNS(tld, dnsIP string) (changed bool, err error) {
	switch detectHostDNSBackend() {
	case hostDNSTailscale:
		return false, nil
	case hostDNSManual:
		return false, ErrManualDNSNeeded
	}
	body := renderResolvedDropin(tld, dnsIP)

	if existing, err := os.ReadFile(resolvedDropinPath); err == nil && bytes.Equal(existing, body) {
		return false, nil
	}

	tmp, err := os.CreateTemp("", "pier-resolved-*.conf")
	if err != nil {
		return false, err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return false, err
	}
	tmp.Close()

	if err := runSudo("install", "-m", "0644", "-D", tmpPath, resolvedDropinPath); err != nil {
		return false, fmt.Errorf("install drop-in (you may need to enter your password): %w", err)
	}
	if err := runSudo("systemctl", "reload-or-restart", "systemd-resolved"); err != nil {
		return false, fmt.Errorf("reload systemd-resolved: %w", err)
	}
	return true, nil
}

func unconfigureHostDNS() (bool, error) {
	if _, err := os.Stat(resolvedDropinPath); errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err := runSudo("rm", "-f", resolvedDropinPath); err != nil {
		return false, err
	}
	if err := runSudo("systemctl", "reload-or-restart", "systemd-resolved"); err != nil {
		return false, err
	}
	return true, nil
}

// manualDNSInstructions returns the shell commands the user should run when
// pier cannot or should not modify host DNS itself. Two flavours: when
// systemd-resolved is the active resolver pier emits a ready-to-paste
// drop-in; otherwise we fall back to a generic guidance that names the
// target IP and lets the user adapt to whichever resolver they run.
func manualDNSInstructions(tld, dnsIP string) string {
	if systemdResolvedActive() {
		body := renderResolvedDropin(tld, dnsIP)
		return fmt.Sprintf(`Run the following as root to route .%s lookups to dnsmasq:

  sudo tee %s >/dev/null <<'EOF'
%s
EOF
  sudo systemctl reload-or-restart systemd-resolved

Verify with:  dig +short @127.0.0.1 anything.%s
`, tld, resolvedDropinPath, string(body), tld)
	}
	return fmt.Sprintf(`pier auto-configures host DNS only on systemd-resolved (Linux) and via tailscale's MagicDNS — neither was detected here.

Configure your resolver so .%s queries forward to %s:53. Examples:
  - NetworkManager + dnsmasq plugin: drop a server=/.%s/%s file under /etc/NetworkManager/dnsmasq.d/
  - resolvconf: append nameserver %s to a hook for the .%s domain
  - /etc/resolv.conf direct: add `+"`nameserver %s`"+` (affects all queries — narrow it via your stack instead)

Verify with:  dig +short @127.0.0.1 anything.%s
`, tld, dnsIP, tld, dnsIP, dnsIP, tld, dnsIP, tld)
}

// systemdResolvedActive checks whether systemd-resolved is running.
func systemdResolvedActive() bool {
	cmd := exec.Command("systemctl", "is-active", "--quiet", "systemd-resolved")
	return cmd.Run() == nil
}

type hostDNSBackend int

const (
	hostDNSManual hostDNSBackend = iota
	hostDNSTailscale
	hostDNSSystemdResolved
)

func selectHostDNSBackend(tailscaleResolvConf, resolvedActive, tailscaleDNSActive bool) hostDNSBackend {
	switch {
	case tailscaleResolvConf:
		return hostDNSTailscale
	case resolvedActive:
		return hostDNSSystemdResolved
	case tailscaleDNSActive:
		return hostDNSTailscale
	default:
		return hostDNSManual
	}
}

func detectHostDNSBackend() hostDNSBackend {
	return selectHostDNSBackend(
		tailscaleOwnsResolvConf(),
		systemdResolvedActive(),
		tailscaleDNSActive(),
	)
}

func tailscaleOwnsResolvConf() bool {
	if body, err := os.ReadFile("/etc/resolv.conf"); err == nil {
		if line, _, _ := strings.Cut(string(body), "\n"); strings.Contains(line, "generated by tailscale") {
			return true
		}
	}
	return false
}

func tailscaleDNSActive() bool {
	out, err := exec.Command("tailscale", "dns", "status").Output()
	if err != nil {
		return false
	}
	return strings.Contains(string(out), "Tailscale DNS: enabled")
}

func checkResolvedDropin(tld string) Check {
	switch detectHostDNSBackend() {
	case hostDNSTailscale:
		return Check{
			Name:   "host DNS routing",
			Status: StatusPass,
			Detail: "tailscale split-DNS forwards ." + tld + " queries (no drop-in needed)",
		}
	case hostDNSManual:
		return Check{
			Name:    "host DNS routing",
			Status:  StatusFail,
			Detail:  "neither systemd-resolved nor Tailscale DNS manages host lookups",
			FixHint: "configure host DNS manually",
		}
	}
	body, err := os.ReadFile(resolvedDropinPath)
	if errors.Is(err, os.ErrNotExist) {
		return Check{
			Name:    "systemd-resolved drop-in",
			Status:  StatusFail,
			Detail:  resolvedDropinPath + " missing",
			FixHint: "pier doctor --fix  (re-runs the sudo install step)",
		}
	}
	if err != nil {
		return Check{Name: "systemd-resolved drop-in", Status: StatusWarn, Detail: err.Error()}
	}
	if !strings.Contains(string(body), "Domains=~"+tld) {
		return Check{
			Name:    "systemd-resolved drop-in",
			Status:  StatusFail,
			Detail:  "Domains=~" + tld + " not found",
			FixHint: "pier doctor --fix",
		}
	}
	return Check{Name: "systemd-resolved drop-in", Status: StatusPass}
}

// needsResolvedRewrite returns true when the on-disk drop-in is missing or
// references a different (TLD, bindIP) than the active config.
func needsResolvedRewrite(tld, bindIP string) bool {
	body, err := os.ReadFile(resolvedDropinPath)
	if err != nil {
		return true
	}
	want := string(renderResolvedDropin(tld, bindIP))
	return string(body) != want
}

func runSudo(args ...string) error {
	cmd := exec.Command("sudo", args...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
